POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Reno Siqueira"
}
 
###



GET http://localhost:3333/courses?orderBy=title


###


GET http://localhost:3333/courses/32b8517f-f0d8-4299-ae30-483f0e722397