POST http://localhost:3333/courses
Content-Type: application/json

{
     "title": "Achorro",
    "description": "au au au "
}
 
###



GET http://localhost:3333/courses?orderBy=title


###


GET http://localhost:3333/courses/eedf4a11-c490-4577-9bc1-457021f34b31